name: playground

x-common-service: &common-service
  restart: unless-stopped
  networks:
    - my-network
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:${GATEWAY_PORT}/actuator/health"]
    interval: 10s
    timeout: 5s
    retries: 5
  env_file:
    - .env

services:
  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    networks:
    - my-network
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy

  auth-service:
    <<: *common-service
    container_name: auth-service
    build: ./auth-service
    ports:
      - "${AUTH_PORT}:8080"

  user-service:
    <<: *common-service
    container_name: user-service
    build: ./user-service
    ports:
      - "${USER_PORT}:8080"
  
  chat-service:
    <<: *common-service
    container_name: chat-service
    build:
      context: ./chat-service
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "${CHAT_PORT}:8080"

# ⚠️ Requirements

# 1. Redis container must be running (name: redis)
# 2. MySQL container must be running (name: mysql)
# 3. Docker network `my-network` must exist
networks:
  my-network:
    external: true
